#spring.application.name= Employee_management
#server.port=8082
#
#  # PostgreSQL database connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
#spring.datasource.username=postgres
#spring.datasource.password=chris2020
#spring.jpa.hibernate.ddl-auto=create
#spring
#
#  # JWT config
#jwt.secret=mySecretKey
#jwt.expiration=86400000
